steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/davec-op-project/gcr.io/app:$_TAG', '.' ]
images:
  - 'us-docker.pkg.dev/davec-op-project/gcr.io/app:$_TAG'
substitutions:
  _TAG: ${TAG_NAME/v/}

  